//****************************************************
// protoc --go_out=. --go-grpc_out=. ./*.proto
// protoc --go_out=. --go-grpc_out=. ./protobuffer-files/*.proto
//****************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: protobuffer-files/math.proto

package pbmath

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Num struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num float64 `protobuf:"fixed64,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Num) Reset() {
	*x = Num{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuffer_files_math_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Num) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Num) ProtoMessage() {}

func (x *Num) ProtoReflect() protoreflect.Message {
	mi := &file_protobuffer_files_math_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Num.ProtoReflect.Descriptor instead.
func (*Num) Descriptor() ([]byte, []int) {
	return file_protobuffer_files_math_proto_rawDescGZIP(), []int{0}
}

func (x *Num) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_protobuffer_files_math_proto protoreflect.FileDescriptor

var file_protobuffer_files_math_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x74, 0x6f, 0x64, 0x6f, 0x61, 0x70, 0x70, 0x22, 0x17, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x32, 0x32, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x23, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x61, 0x70, 0x70,
	0x2e, 0x4e, 0x75, 0x6d, 0x1a, 0x0c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x61, 0x70, 0x70, 0x2e, 0x4e,
	0x75, 0x6d, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x62, 0x6d, 0x61, 0x74, 0x68,
	0x3b, 0x70, 0x62, 0x6d, 0x61, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuffer_files_math_proto_rawDescOnce sync.Once
	file_protobuffer_files_math_proto_rawDescData = file_protobuffer_files_math_proto_rawDesc
)

func file_protobuffer_files_math_proto_rawDescGZIP() []byte {
	file_protobuffer_files_math_proto_rawDescOnce.Do(func() {
		file_protobuffer_files_math_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuffer_files_math_proto_rawDescData)
	})
	return file_protobuffer_files_math_proto_rawDescData
}

var file_protobuffer_files_math_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuffer_files_math_proto_goTypes = []interface{}{
	(*Num)(nil), // 0: todoapp.Num
}
var file_protobuffer_files_math_proto_depIdxs = []int32{
	0, // 0: todoapp.MathService.Add:input_type -> todoapp.Num
	0, // 1: todoapp.MathService.Add:output_type -> todoapp.Num
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuffer_files_math_proto_init() }
func file_protobuffer_files_math_proto_init() {
	if File_protobuffer_files_math_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuffer_files_math_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Num); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuffer_files_math_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuffer_files_math_proto_goTypes,
		DependencyIndexes: file_protobuffer_files_math_proto_depIdxs,
		MessageInfos:      file_protobuffer_files_math_proto_msgTypes,
	}.Build()
	File_protobuffer_files_math_proto = out.File
	file_protobuffer_files_math_proto_rawDesc = nil
	file_protobuffer_files_math_proto_goTypes = nil
	file_protobuffer_files_math_proto_depIdxs = nil
}
